"""
Reformat training data into a report export so that it can be imported into TRAM.

The target format is:
{
    "sentence-text": ["<technique-id-1>", "<technique-id-2>", "<technique-id-N>"]
}

The original format is:
    * negative_data.json - A file with sentences that have no mappings. This is a simple list of strings.
    * all_analyzed_reports.json - A file with mappings. Has the following structure:
    {
        "<attack-technique-description>": ["<sentence-1>", "<sentence-2>", "<sentence-n>"],  # OR
        "<description-1 description-2 description-N -multi>": {  # Can use key.endswith('-multi') to test
        "technique_names": [
                "description-1",
                "description-2",
                "description-N",
            ],
            "sentances": [  # Note the word sentences is misspelled as sentances
                "<sentence-1>",
                "<sentence-2>",
                "<sentence-N>"
            ]
        }
    }

The target format is defined by tram.serializers.ReportExportSerializer
"""

import itertools
import json
import logging
import os
import pathlib
import sys
from datetime import datetime
from functools import partial

import django

sys.path.append("/Users/ankitchauhan/Drive/tram/src/")
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "tram.settings")
django.setup()

from tram.serializers import ReportExportSerializer  # noqa: E402

parent_directory = os.getcwd()
file_path = (
    parent_directory + "/data/training/training-dataset/tram_existing_dataset_.txt"
)
outfile = parent_directory + "/data/training/bootstrap-training-data.json"
logger = logging.getLogger(__name__)

arr = pathlib.Path(__file__).parent.resolve()

# ATTACK_LOOKUP = {  # A mapping of attack descriptions to technique IDs
#     "drive-by compromise": "T1189",
#     "system information discovery": "T1082",
#     "new service": "T1543",
#     "service execution": "T1569.002",
#     "command-line interface": "T1059",  # Maps to: T1059 - Command and Scripting Interpreter
#     "obfuscated files or information": "T1027",
#     "custom cryptographic protocol": "T1573",  # Maps to: T1573 - Encrypted Channel
#     "system network configuration discovery": "T1016",
#     "web shell": "T1505.003",
#     "application window discovery": "T1010",
#     "file deletion": "T1070.004",  # Technique that became a subtechnique
#     "standard application layer protocol": "T1071",
#     "web service": "T1102",
#     "exfiltration over command and control channel": "T1041",
#     "fallback channels": "T1008",
#     "bypass user account control": "T1548.002",  # Technique that became a subtechnique
#     "system time discovery": "T1124",
#     "deobfuscate/decode files or information": "T1140",
#     "disabling security tools": "T1562.001",  # Maps to: T1562.001 - Impair Defenses: Disable or Modify Tools
#     "registry run keys / startup folder": "T1547.001",
#     "remote file copy": "T1105",  # Maps to: T1105 - Ingress Tool Transfer
#     "dll search order hijacking": "T1574.001",
#     "screen capture": "T1113",
#     "file and directory discovery": "T1083",
#     "tor": "S0183",  # Software??
#     "shortcut modification": "T1547.009",
#     "remote services": "T1021",
#     "connection proxy": "T1090",
#     "data encoding": "T1132",
#     "spearphishing link": "T1566.002",
#     "spearphishing attachment": "T1566.001",
#     "arp": "S0099",
#     "user execution": "T1204",
#     "process hollowing": "T1055.012",
#     "execution through api": "T1106",  # Maps to T1106 - Native API
#     "masquerading": "T1036",
#     "code signing": "T1553.002",
#     "standard cryptographic protocol": "T1521",
#     "scripting": "T1059",
#     "remote system discovery": "T1018",
#     "credential dumping": "T1003",
#     "exploitation for client execution": "T1203",
#     "exploitation for privilege escalation": "T1068",
#     "security software discovery": "T1518.001",
#     "data from local system": "T1533",
#     "remote desktop protocol": "T1021.001",
#     "data compressed": "T1560",  # Maps to T1560 - Archive Collected Data
#     "software packing": "T1027.002",
#     "ping": "S0097",
#     "brute force": "T1110",
#     "commonly used port": "T1571",
#     "modify registry": "T1112",
#     "uncommonly used port": "T1571",
#     "process injection": "T1055",
#     "timestomp": "T1070.006",
#     "windows management instrumentation": "T1047",
#     "data staged": "T1074",
#     "rundll32": "T1218.011",
#     "regsvr32": "T1218.010",
#     "account discovery": "T1087",
#     "process discovery": "T1057",
#     "clipboard data": "T1115",
#     "binary padding": "T1027.001",
#     "pass the hash": "T1550.002",
#     "network service scanning": "T1046",
#     "system service discovery": "T1007",
#     "data encrypted": "T1486",
#     "system network connections discovery": "T1049",
#     "windows admin shares": "T1021.002",
#     "system owner/user discovery": "T1033",
#     "launch agent": "T1543.001",
#     "permission groups discovery": "T1069",
#     "indicator removal on host": "T1070",
#     "input capture": "T1056",
#     "virtualization/sandbox evasion": "T1497.001",
#     "dll side-loading": "T1574.002",
#     "scheduled task": "T1053",
#     "access token manipulation": "T1134",
#     "powershell": "T1546.013",
#     "exfiltration over alternative protocol": "T1048",
#     "hidden files and directories": "T1564.001",
#     "network share discovery": "T1135",
#     "query registry": "T1012",
#     "credentials in files": "T1552.001",
#     "audio capture": "T1123",
#     "video capture": "T1125",
#     "peripheral device discovery": "T1120",
#     "spearphishing via service": "T1566.003",
#     "data encrypted for impact": "T1486",
#     "data destruction": "T1485",
#     "template injection": "T1221",
#     "inhibit system recovery": "T1490",
#     "create account": "T1136",
#     "exploitation of remote services": "T1210",
#     "valid accounts": "T1078",
#     "dynamic data exchange": "T1559.002",
#     "office application startup": "T1137",
#     "data obfuscation": "T1001",
#     "domain trust discovery": "T1482",
#     "email collection": "T1114",
#     "man in the browser": "T1185",
#     "data from removable media": "T1025",
#     "bootkit": "T1542.003",
#     "logon scripts": "T1037",
#     "execution through module load": "T1129",
#     "llmnr/nbt-ns poisoning and relay": "T1557.001",
#     "external remote services": "T1133",
#     "domain fronting": "T1090.004",
#     "sid-history injection": "T1134.005",
#     "service stop": "T1489",
#     "disk structure wipe": "T1561.002",
#     "credentials in registry": "T1552.002",
#     "appinit dlls": "T1546.010",
#     "exploit public-facing application": "T1190",
#     "remote access tools": "T1219",
#     "signed binary proxy execution": "T1218",
#     "appcert dlls": "T1546.009",
#     "winlogon helper dll": "T1547.004",
#     "file permissions modification": "T1222",
#     "hooking": "T1056.004",
#     "system firmware": "T1542.001",
#     "lsass driver": "T1547.008",
#     "distributed component object model": "T1021.003",
#     "cmstp": "T1218.003",
#     "execution guardrails": "T1480",
#     "component object model hijacking": "T1546.015",
#     "accessibility features": "T1546.008",  # TODO: Help wanted
#     "keychain": "T1555.001",
#     "mshta": "T1218.005",
#     "pass the ticket": "T1550.003",
#     "kerberoasting": "T1558.003",
#     "password policy discovery": "T1201",
#     "local job scheduling": "T1053.001",
#     "windows remote management": "T1021.006",
#     "bits jobs": "T1197",
#     "data from information repositories": "T1213",
#     "lc_load_dylib addition": "T1546.006",
#     "histcontrol": "T1562.003",
#     "file system logical offsets": "T1006",
#     "regsvcs/regasm": "T1218.009",
#     "exploitation for credential access": "T1212",
#     "sudo": "T1548.003",
#     "installutil": "T1218.004",
#     "query registry ": "T1012",
#     "launchctl": "T1569.001",
#     ".bash_profile and .bashrc": "T1546.004",
#     "applescript": "T1059.002",
#     "emond": "T1546.014",
#     "control panel items": "T1218.002",
#     "application shimming": "T1546.011",
# }

ATTACK_LOOKUP = {
    "obfuscated files or information": "T1027",
    "ingress tool transfer": "T1105",
    "system information discovery": "T1082",
    "command and scripting interpreter: windows command shell": "T1059.003",
    "data encrypted for impact": "T1486",
    "file and directory discovery": "T1083",
    "native api": "T1106",
    "user execution: malicious file": "T1204.002",
    "process discovery": "T1057",
    "application layer protocol: web protocols": "T1071.001",
    "phishing: spearphishing attachment": "T1566.001",
    "indicator removal on host: file deletion": "T1070.004",
    "deobfuscate/decode files or information": "T1140",
    "command and scripting interpreter: powershell": "T1059.001",
    "system network configuration discovery": "T1016",
    "boot or logon autostart execution: registry run keys / startup folder": "T1547.001",
    "command and scripting interpreter: visual basic": "T1059.005",
    "modify registry": "T1112",
    "data destruction": "T1485",
    "impair defenses: disable or modify tools": "T1562.001",
    "windows management instrumentation": "T1047",
    "masquerading: match legitimate name or location": "T1036.005",
    "service stop": "T1489",
    "inhibit system recovery": "T1490",
    "scheduled task/job: scheduled task": "T1053.005",
    "system owner/user discovery": "T1033",
    "data from local system": "T1005",
    "exfiltration over c2 channel": "T1041",
    "network share discovery": "T1135",
    "create or modify system process: windows service": "T1543.003",
    "phishing: spearphishing link": "T1566.002",
    "system binary proxy execution: rundll32": "T1218.011",
    "remote system discovery": "T1018",
    "obfuscated files or information: software packing": "T1027.002",
    "user execution: malicious link": "T1204.001",
    "process injection": "T1055",
    "input capture: keylogging": "T1056.001",
    "exploitation for client execution": "T1203",
    "software discovery: security software discovery": "T1518.001",
    "disk wipe: disk structure wipe": "T1561.002",
    "system services: service execution": "T1569.002",
    "system network connections discovery": "T1049",
    "credentials from password stores: credentials from web browsers": "T1555.003",
    "screen capture": "T1113",
    "masquerading": "T1036",
    "query registry": "T1012",
    "drive-by compromise": "T1189",
    "remote services: smb/windows admin shares": "T1021.002",
    "system shutdown/reboot": "T1529",
    "subvert trust controls: code signing": "T1553.002",
    "process injection: dynamic-link library injection": "T1055.001",
    "abuse elevation control mechanism: bypass user account control": "T1548.002",
    "os credential dumping: lsass memory": "T1003.001",
    "command and scripting interpreter: javascript": "T1059.007",
    "masquerading: masquerade task or service": "T1036.004",
    "system time discovery": "T1124",
    "indicator removal on host: clear windows event logs": "T1070.001",
    "obtain capabilities: tool": "T1588.002",
    "system location discovery: system language discovery": "T1614.001",
    "valid accounts": "T1078",
    "encrypted channel: symmetric cryptography": "T1573.001",
    "lateral tool transfer": "T1570",
    "network service discovery": "T1046",
    "command and scripting interpreter": "T1059",
    "data encoding: standard encoding": "T1132.001",
    "exploitation of remote services": "T1210",
    "system binary proxy execution: mshta": "T1218.005",
    "automated collection": "T1119",
    "web service: bidirectional communication": "T1102.002",
    "access token manipulation": "T1134",
    "indicator removal on host": "T1070",
    "system binary proxy execution: msiexec": "T1218.007",
    "hijack execution flow: dll side-loading": "T1574.002",
    "non-standard port": "T1571",
    "remote services: remote desktop protocol": "T1021.001",
    "system service discovery": "T1007",
    "virtualization/sandbox evasion: time based evasion": "T1497.003",
    "acquire infrastructure: domains": "T1583.001",
    "data staged: local data staging": "T1074.001",
    "system binary proxy execution: regsvr32": "T1218.010",
    "hide artifacts: hidden window": "T1564.003",
    "obfuscated files or information: steganography": "T1027.003",
    "peripheral device discovery": "T1120",
    "remote access software": "T1219",
    "fallback channels": "T1008",
    "archive collected data": "T1560",
    "encrypted channel: asymmetric cryptography": "T1573.002",
    "valid accounts: domain accounts": "T1078.002",
    "obfuscated files or information: binary padding": "T1027.001",
    "hide artifacts: hidden files and directories": "T1564.001",
    "clipboard data": "T1115",
    "brute force": "T1110",
    "disk wipe: disk content wipe": "T1561.001",
    "indicator removal on host: timestomp": "T1070.006",
    "virtualization/sandbox evasion: system checks": "T1497.001",
    "inter-process communication: dynamic data exchange": "T1559.002",
    "external remote services": "T1133",
    "unsecured credentials: credentials in files": "T1552.001",
    "command and scripting interpreter: python": "T1059.006",
    "exploit public-facing application": "T1190",
    "virtualization/sandbox evasion": "T1497",
    "application window discovery": "T1010",
    "access token manipulation: token impersonation/theft": "T1134.001",
    "supply chain compromise: compromise software supply chain": "T1195.002",
    "account discovery: local account": "T1087.001",
    "server software component: web shell": "T1505.003",
    "web service: dead drop resolver": "T1102.001",
    "hijack execution flow: dll search order hijacking": "T1574.001",
    "web service": "T1102",
    "boot or logon autostart execution: shortcut modification": "T1547.009",
    "data manipulation: transmitted data manipulation": "T1565.002",
    "archive collected data: archive via utility": "T1560.001",
    "software discovery": "T1518",
    "non-application layer protocol": "T1095",
    "account discovery: domain account": "T1087.002",
    "access token manipulation: create process with token": "T1134.002",
    "defacement: internal defacement": "T1491.001",
    "exploitation for privilege escalation": "T1068",
    "brute force: password spraying": "T1110.003",
    "create account": "T1136",
    "proxy: external proxy": "T1090.002",
    "exfiltration over web service: exfiltration to cloud storage": "T1567.002",
    "process injection: process hollowing": "T1055.012",
    "account manipulation": "T1098",
    "user execution": "T1204",
    "pre-os boot: bootkit": "T1542.003",
    "os credential dumping": "T1003",
    "file and directory permissions modification: windows file and directory permissions modification": "T1222.001",
    "template injection": "T1221",
    "remote services: vnc": "T1021.005",
    "shared modules": "T1129",
    "domain policy modification: group policy modification": "T1484.001",
    "develop capabilities: malware": "T1587.001",
    "impair defenses: disable or modify system firewall": "T1562.004",
    "gather victim identity information: email addresses": "T1589.002",
    "account discovery": "T1087",
    "scheduled task/job: cron": "T1053.003",
    "hide artifacts: ntfs file attributes": "T1564.004",
    "phishing for information: spearphishing link": "T1598.003",
    "phishing": "T1566",
    "permission groups discovery: domain groups": "T1069.002",
    "system binary proxy execution: compiled html file": "T1218.001",
    "account discovery: email account": "T1087.003",
    "proxy: internal proxy": "T1090.001",
    "establish accounts: email accounts": "T1585.002",
    "acquire infrastructure: web services": "T1583.006",
    "data from network shared drive": "T1039",
    "permission groups discovery": "T1069",
    "trusted relationship": "T1199",
    "browser session hijacking": "T1185",
    "dynamic resolution": "T1568",
    "domain trust discovery": "T1482",
    "stage capabilities: upload malware": "T1608.001",
    "account access removal": "T1531",
    "bits jobs": "T1197",
    "establish accounts: social media accounts": "T1585.001",
    "taint shared content": "T1080",
    "obtain capabilities: code signing certificates": "T1588.003",
    "remote services: ssh": "T1021.004",
    "proxy": "T1090",
    "video capture": "T1125",
    "exfiltration over alternative protocol: exfiltration over unencrypted non-c2 protocol": "T1048.003",
    "credentials from password stores": "T1555",
    "system services": "T1569",
    "replication through removable media": "T1091",
    "application layer protocol: dns": "T1071.004",
    "application layer protocol: file transfer protocols": "T1071.002",
    "brute force: password guessing": "T1110.001",
    "remote services": "T1021",
    "multi-stage channels": "T1104",
    "application layer protocol": "T1071",
    "inter-process communication: component object model": "T1559.001",
    "data manipulation: stored data manipulation": "T1565.001",
    "valid accounts: local accounts": "T1078.003",
    "automated exfiltration": "T1020",
    "firmware corruption": "T1495",
    "reflective code loading": "T1620",
    "internal spearphishing": "T1534",
    "network sniffing": "T1040",
    "proxy: multi-hop proxy": "T1090.003",
    "phishing: spearphishing via service": "T1566.003",
    "impair defenses: safe mode boot": "T1562.009",
    "acquire infrastructure: server": "T1583.004",
    "xsl script processing": "T1220",
    "email collection: remote email collection": "T1114.002",
    "unsecured credentials: credentials in registry": "T1552.002",
    "compromise client software binary": "T1554",
    "scheduled task/job": "T1053",
    "scheduled transfer": "T1029",
    "os credential dumping: lsa secrets": "T1003.004",
    "permission groups discovery: local groups": "T1069.001",
    "archive collected data: archive via custom method": "T1560.003",
    "compromise infrastructure: domains": "T1584.001",
    "dynamic resolution: domain generation algorithms": "T1568.002",
    "impair defenses": "T1562",
    "file and directory permissions modification": "T1222",
    "create or modify system process": "T1543",
    "masquerading: invalid code signature": "T1036.001",
    "masquerading: rename system utilities": "T1036.003",
    "command and scripting interpreter: unix shell": "T1059.004",
    "indicator removal on host: clear command history": "T1070.003",
    "abuse elevation control mechanism": "T1548",
    "impair defenses: disable windows event logging": "T1562.002",
    "compromise infrastructure: server": "T1584.004",
    "event triggered execution: accessibility features": "T1546.008",
    "create account: local account": "T1136.001",
    "data from removable media": "T1025",
    "application layer protocol: mail protocols": "T1071.003",
    "data obfuscation: protocol impersonation": "T1001.003",
    "input capture: gui input capture": "T1056.002",
    "office application startup": "T1137",
    "browser bookmark discovery": "T1217",
    "protocol tunneling": "T1572",
    "adversary-in-the-middle: llmnr/nbt-ns poisoning and smb relay": "T1557.001",
    "active scanning: vulnerability scanning": "T1595.002",
    "event triggered execution: windows management instrumentation event subscription": "T1546.003",
    "data staged: remote data staging": "T1074.002",
    "os credential dumping: security account manager": "T1003.002",
    "steal web session cookie": "T1539",
    "impair defenses: impair command history logging": "T1562.003",
    "execution guardrails": "T1480",
    "system network configuration discovery: internet connection discovery": "T1016.001",
    "system binary proxy execution": "T1218",
    "server software component: sql stored procedures": "T1505.001",
    "data manipulation: runtime data manipulation": "T1565.003",
    "adversary-in-the-middle": "T1557",
    "impair defenses: indicator blocking": "T1562.006",
    "valid accounts: default accounts": "T1078.001",
    "create or modify system process: launch daemon": "T1543.004",
    "hijack execution flow: dynamic linker hijacking": "T1574.006",
    "encrypted channel": "T1573",
    "archive collected data: archive via library": "T1560.002",
    "brute force: password cracking": "T1110.002",
    "obfuscated files or information: compile after delivery": "T1027.004",
    "audio capture": "T1123",
    "system binary proxy execution: installutil": "T1218.004",
    "obtain capabilities: digital certificates": "T1588.004",
    "gather victim identity information: employee names": "T1589.003",
    "search victim-owned websites": "T1594",
    "boot or logon autostart execution": "T1547",
    "remote service session hijacking: rdp hijacking": "T1563.002",
    "supply chain compromise: compromise software dependencies and development tools": "T1195.001",
    "hide artifacts: run virtual instance": "T1564.006",
    "os credential dumping: ntds": "T1003.003",
    "compromise accounts: email accounts": "T1586.002",
    "phishing for information: spearphishing attachment": "T1598.002",
    "valid accounts: cloud accounts": "T1078.004",
    "os credential dumping: cached domain credentials": "T1003.005",
    "input capture: credential api hooking": "T1056.004",
    "web service: one-way communication": "T1102.003",
    "search open websites/domains: social media": "T1593.001",
    "subvert trust controls: code signing policy modification": "T1553.006",
    "credentials from password stores: password managers": "T1555.005",
    "gather victim network information: domain properties": "T1590.001",
    "gather victim org information": "T1591",
    "gather victim org information: business relationships": "T1591.002",
    "gather victim host information: software": "T1592.002",
    "stage capabilities: upload tool": "T1608.002",
    "use alternate authentication material: pass the ticket": "T1550.003",
    "steal or forge kerberos tickets: kerberoasting": "T1558.003",
    "virtualization/sandbox evasion: user activity based checks": "T1497.002",
    "dynamic resolution: fast flux dns": "T1568.001",
    "execution guardrails: environmental keying": "T1480.001",
    "obfuscated files or information: indicator removal from tools": "T1027.005",
    "boot or logon initialization scripts: logon script (windows)": "T1037.001",
    "exfiltration over alternative protocol": "T1048",
    "software deployment tools": "T1072",
    "email collection": "T1114",
    "email collection: email forwarding rule": "T1114.003",
    "subvert trust controls: mark-of-the-web bypass": "T1553.005",
    "unsecured credentials: private keys": "T1552.004",
    "exfiltration over web service": "T1567",
    "phishing for information": "T1598",
    "use alternate authentication material: pass the hash": "T1550.002",
    "obtain capabilities: vulnerabilities": "T1588.006",
    "search open websites/domains": "T1593",
    "data obfuscation: steganography": "T1001.002",
    "brute force: credential stuffing": "T1110.004",
    "create account: domain account": "T1136.002",
    "indirect command execution": "T1202",
    "defacement: external defacement": "T1491.002",
    "compromise infrastructure: botnet": "T1584.005",
    "endpoint denial of service": "T1499",
    "hijack execution flow: kernelcallbacktable": "T1574.013",
    "gather victim org information: identify roles": "T1591.004",
    "server software component: transport agent": "T1505.002",
    "endpoint denial of service: application or system exploitation": "T1499.004",
    "hijack execution flow: services file permissions weakness": "T1574.010",
    "obtain capabilities: malware": "T1588.001",
    "unsecured credentials": "T1552",
    "system services: launchctl": "T1569.001",
    "resource hijacking": "T1496",
    "gather victim identity information: credentials": "T1589.001",
    "domain policy modification: domain trust modification": "T1484.002",
    "system location discovery": "T1614",
    "use alternate authentication material": "T1550",
    "rootkit": "T1014",
    "email collection: local email collection": "T1114.001",
    "data from information repositories": "T1213",
    "data obfuscation: junk data": "T1001.001",
    "os credential dumping: dcsync": "T1003.006",
    "process injection: process doppelgänging": "T1055.013",
    "indicator removal on host: network share connection removal": "T1070.005",
    "data staged": "T1074",
    "trusted developer utilities proxy execution: msbuild": "T1127.001",
    "office application startup: office template macros": "T1137.001",
    "office application startup: outlook home page": "T1137.004",
    "exploitation for defense evasion": "T1211",
    "system binary proxy execution: odbcconf": "T1218.008",
    "system binary proxy execution: regsvcs/regasm": "T1218.009",
    "file and directory permissions modification: linux and mac file and directory permissions modification": "T1222.002",
    "use alternate authentication material: web session cookie": "T1550.004",
    "domain policy modification": "T1484",
    "network denial of service": "T1498",
    "create or modify system process: launch agent": "T1543.001",
    "event triggered execution: application shimming": "T1546.011",
    "event triggered execution: powershell profile": "T1546.013",
    "debugger evasion": "T1622",
    "credentials from password stores: windows credential manager": "T1555.004",
    "stage capabilities: drive-by target": "T1608.004",
    "boot or logon autostart execution: winlogon helper dll": "T1547.004",
    "abuse elevation control mechanism: setuid and setgid": "T1548.001",
    "boot or logon autostart execution: lsass driver": "T1547.008",
    "hijack execution flow": "T1574",
    "obtain capabilities": "T1588",
    "phishing for information: spearphishing service": "T1598.001",
    "unsecured credentials: bash history": "T1552.003",
    "boot or logon autostart execution: print processors": "T1547.012",
    "abuse elevation control mechanism: elevated execution with prompt": "T1548.004",
    "supply chain compromise": "T1195",
    "data obfuscation": "T1001",
    "exfiltration over other network medium": "T1011",
    "boot or logon initialization scripts": "T1037",
    "boot or logon initialization scripts: login hook": "T1037.002",
    "process injection: thread local storage": "T1055.005",
    "process injection: proc memory": "T1055.009",
    "process injection: extra window memory injection": "T1055.011",
    "command and scripting interpreter: applescript": "T1059.002",
    "account manipulation: ssh authorized keys": "T1098.004",
    "trusted developer utilities proxy execution": "T1127",
    "data encoding": "T1132",
    "access token manipulation: make and impersonate token": "T1134.003",
    "access token manipulation: sid-history injection": "T1134.005",
    "traffic signaling": "T1205",
    "exploitation for credential access": "T1212",
    "data from information repositories: confluence": "T1213.001",
    "boot or logon autostart execution: kernel modules and extensions": "T1547.006",
    "abuse elevation control mechanism: sudo and sudo caching": "T1548.003",
    "subvert trust controls": "T1553",
    "modify authentication process: network device authentication": "T1556.004",
    "adversary-in-the-middle: arp cache poisoning": "T1557.002",
    "steal or forge kerberos tickets": "T1558",
    "remote service session hijacking": "T1563",
    "plist file modification": "T1647",
    "hide artifacts: hidden users": "T1564.002",
    "remote services: windows remote management": "T1021.006",
    "data transfer size limits": "T1030",
    "masquerading: right-to-left override": "T1036.002",
    "account manipulation: additional email delegate permissions": "T1098.002",
    "forced authentication": "T1187",
    "event triggered execution: component object model hijacking": "T1546.015",
    "use alternate authentication material: application access token": "T1550.001",
    "gather victim identity information": "T1589",
    "steal application access token": "T1528",
    "obfuscated files or information: html smuggling": "T1027.006",
    "masquerading: double file extension": "T1036.007",
    "exfiltration over alternative protocol: exfiltration over asymmetric encrypted non-c2 protocol": "T1048.002",
    "exfiltration over physical medium: exfiltration over usb": "T1052.001",
    "scheduled task/job: at": "T1053.002",
    "process injection: asynchronous procedure call": "T1055.004",
    "input capture": "T1056",
    "account discovery: cloud account": "T1087.004",
    "proxy: domain fronting": "T1090.004",
    "account manipulation: device registration": "T1098.005",
    "create account: cloud account": "T1136.003",
    "office application startup: add-ins": "T1137.006",
    "browser extensions": "T1176",
    "password policy discovery": "T1201",
    "system binary proxy execution: cmstp": "T1218.003",
    "event triggered execution: appinit dlls": "T1546.010",
    "forge web credentials: saml tokens": "T1606.002",
    "credentials from password stores: securityd memory": "T1555.002",
    "subvert trust controls: gatekeeper bypass": "T1553.001",
    "acquire infrastructure": "T1583",
    "create or modify system process: systemd service": "T1543.002",
    "inter-process communication: xpc services": "T1559.003",
    "hide artifacts": "T1564",
    "server software component: terminal services dll": "T1505.005",
    "acquire infrastructure: botnet": "T1583.005",
    "exfiltration over web service: exfiltration to code repository": "T1567.001",
    "system binary proxy execution: mmc": "T1218.014",
    "develop capabilities": "T1587",
    "stage capabilities": "T1608",
    "event triggered execution: screensaver": "T1546.002",
    "compromise infrastructure": "T1584",
    "establish accounts": "T1585",
    "compromise accounts: social media accounts": "T1586.001",
    "cloud service dashboard": "T1538",
    "active scanning: scanning ip blocks": "T1595.001",
    "pre-os boot: component firmware": "T1542.002",
    "boot or logon autostart execution: time providers": "T1547.003",
    "inter-process communication": "T1559",
    "stage capabilities: install digital certificate": "T1608.003",
    "event triggered execution: netsh helper dll": "T1546.007",
    "event triggered execution: emond": "T1546.014",
    "steal or forge kerberos tickets: silver ticket": "T1558.002",
    "acquire infrastructure: virtual private server": "T1583.003",
    "compromise infrastructure: virtual private server": "T1584.003",
    "search open websites/domains: search engines": "T1593.002",
    "defacement": "T1491",
    "cloud service discovery": "T1526",
    "event triggered execution: appcert dlls": "T1546.009",
    "subvert trust controls: install root certificate": "T1553.004",
    "gather victim network information": "T1590",
    "gather victim network information: network security appliances": "T1590.006",
    "gather victim org information: determine physical locations": "T1591.001",
    "gather victim host information: hardware": "T1592.001",
    "search closed sources: purchase technical data": "T1597.002",
    "forge web credentials: web cookies": "T1606.001",
    "cloud storage object discovery": "T1619",
    "process injection: portable executable injection": "T1055.002",
    "permission groups discovery: cloud groups": "T1069.003",
    "communication through removable media": "T1092",
    "account manipulation: additional cloud credentials": "T1098.001",
    "account manipulation: additional cloud roles": "T1098.003",
    "multi-factor authentication interception": "T1111",
    "data encoding: non-standard encoding": "T1132.002",
    "access token manipulation: parent pid spoofing": "T1134.004",
    "office application startup: office test": "T1137.002",
    "data from information repositories: sharepoint": "T1213.002",
    "data from information repositories: code repositories": "T1213.003",
    "system script proxy execution: pubprn": "T1216.001",
    "network denial of service: reflection amplification": "T1498.002",
    "server software component": "T1505",
    "implant internal image": "T1525",
    "event triggered execution": "T1546",
    "event triggered execution: image file execution options injection": "T1546.012",
    "boot or logon autostart execution: active setup": "T1547.014",
    "unsecured credentials: cloud instance metadata api": "T1552.005",
    "subvert trust controls: sip and trust provider hijacking": "T1553.003",
    "modify authentication process: reversible encryption": "T1556.005",
    "steal or forge kerberos tickets: golden ticket": "T1558.001",
    "disk wipe": "T1561",
    "impair defenses: disable cloud logs": "T1562.008",
    "hide artifacts: vba stomping": "T1564.007",
    "data manipulation": "T1565",
    "hijack execution flow: executable installer file permissions weakness": "T1574.005",
    "hijack execution flow: cor_profiler": "T1574.012",
    "acquire infrastructure: dns server": "T1583.002",
    "compromise infrastructure: dns server": "T1584.002",
    "compromise accounts": "T1586",
    "develop capabilities: code signing certificates": "T1587.002",
    "obtain capabilities: exploits": "T1588.005",
    "gather victim network information: network topology": "T1590.004",
    "gather victim org information: identify business tempo": "T1591.003",
    "gather victim host information: client configurations": "T1592.004",
    "forge web credentials": "T1606",
    "container and resource discovery": "T1613",
    "multi-factor authentication request generation": "T1621",
    "os credential dumping: proc filesystem": "T1003.007",
    "os credential dumping: /etc/passwd and /etc/shadow": "T1003.008",
    "direct volume access": "T1006",
    "exfiltration over other network medium: exfiltration over bluetooth": "T1011.001",
    "automated exfiltration: traffic duplication": "T1020.001",
    "remote services: distributed component object model": "T1021.003",
    "masquerading: space after filename": "T1036.006",
    "boot or logon initialization scripts: network logon script": "T1037.003",
    "boot or logon initialization scripts: rc scripts": "T1037.004",
    "boot or logon initialization scripts: startup items": "T1037.005",
    "exfiltration over alternative protocol: exfiltration over symmetric encrypted non-c2 protocol": "T1048.001",
    "exfiltration over physical medium": "T1052",
    "scheduled task/job: systemd timers": "T1053.006",
    "scheduled task/job: container orchestration job": "T1053.007",
    "process injection: thread execution hijacking": "T1055.003",
    "process injection: ptrace system calls": "T1055.008",
    "process injection: vdso hijacking": "T1055.014",
    "process injection: listplanting": "T1055.015",
    "input capture: web portal capture": "T1056.003",
    "command and scripting interpreter: network device cli": "T1059.008",
    "indicator removal on host: clear linux or mac system logs": "T1070.002",
    "office application startup: outlook forms": "T1137.003",
    "office application startup: outlook rules": "T1137.005",
    "supply chain compromise: compromise hardware supply chain": "T1195.003",
    "hardware additions": "T1200",
    "user execution: malicious image": "T1204.003",
    "traffic signaling: port knocking": "T1205.001",
    "rogue domain controller": "T1207",
    "system script proxy execution": "T1216",
    "system binary proxy execution: control panel": "T1218.002",
    "system binary proxy execution: verclsid": "T1218.012",
    "system binary proxy execution: mavinject": "T1218.013",
    "network denial of service: direct network flood": "T1498.001",
    "endpoint denial of service: os exhaustion flood": "T1499.001",
    "endpoint denial of service: service exhaustion flood": "T1499.002",
    "endpoint denial of service: application exhaustion flood": "T1499.003",
    "server software component: iis components": "T1505.004",
    "data from cloud storage object": "T1530",
    "unused/unsupported cloud regions": "T1535",
    "transfer data to cloud account": "T1537",
    "pre-os boot": "T1542",
    "pre-os boot: system firmware": "T1542.001",
    "pre-os boot: rommonkit": "T1542.004",
    "pre-os boot: tftp boot": "T1542.005",
    "event triggered execution: change default file association": "T1546.001",
    "event triggered execution: unix shell configuration modification": "T1546.004",
    "event triggered execution: trap": "T1546.005",
    "event triggered execution: lc_load_dylib addition": "T1546.006",
    "boot or logon autostart execution: authentication package": "T1547.002",
    "boot or logon autostart execution: security support provider": "T1547.005",
    "boot or logon autostart execution: re-opened applications": "T1547.007",
    "boot or logon autostart execution: port monitors": "T1547.010",
    "boot or logon autostart execution: xdg autostart entries": "T1547.013",
    "boot or logon autostart execution: login items": "T1547.015",
    "unsecured credentials: group policy preferences": "T1552.006",
    "unsecured credentials: container api": "T1552.007",
    "credentials from password stores: keychain": "T1555.001",
    "modify authentication process": "T1556",
    "modify authentication process: domain controller authentication": "T1556.001",
    "modify authentication process: password filter dll": "T1556.002",
    "modify authentication process: pluggable authentication modules": "T1556.003",
    "adversary-in-the-middle: dhcp spoofing": "T1557.003",
    "steal or forge kerberos tickets: as-rep roasting": "T1558.004",
    "impair defenses: disable or modify cloud firewall": "T1562.007",
    "impair defenses: downgrade attack": "T1562.010",
    "remote service session hijacking: ssh hijacking": "T1563.001",
    "hide artifacts: hidden file system": "T1564.005",
    "hide artifacts: email hiding rules": "T1564.008",
    "hide artifacts: resource forking": "T1564.009",
    "hide artifacts: process argument spoofing": "T1564.010",
    "dynamic resolution: dns calculation": "T1568.003",
    "hijack execution flow: dylib hijacking": "T1574.004",
    "hijack execution flow: path interception by path environment variable": "T1574.007",
    "hijack execution flow: path interception by search order hijacking": "T1574.008",
    "hijack execution flow: path interception by unquoted path": "T1574.009",
    "hijack execution flow: services registry permissions weakness": "T1574.011",
    "modify cloud compute infrastructure": "T1578",
    "modify cloud compute infrastructure: create snapshot": "T1578.001",
    "modify cloud compute infrastructure: create cloud instance": "T1578.002",
    "modify cloud compute infrastructure: delete cloud instance": "T1578.003",
    "modify cloud compute infrastructure: revert cloud instance": "T1578.004",
    "cloud infrastructure discovery": "T1580",
    "compromise infrastructure: web services": "T1584.006",
    "develop capabilities: digital certificates": "T1587.003",
    "develop capabilities: exploits": "T1587.004",
    "gather victim network information: dns": "T1590.002",
    "gather victim network information: network trust dependencies": "T1590.003",
    "gather victim network information: ip addresses": "T1590.005",
    "gather victim host information": "T1592",
    "gather victim host information: firmware": "T1592.003",
    "active scanning": "T1595",
    "active scanning: wordlist scanning": "T1595.003",
    "search open technical databases": "T1596",
    "search open technical databases: dns/passive dns": "T1596.001",
    "search open technical databases: whois": "T1596.002",
    "search open technical databases: digital certificates": "T1596.003",
    "search open technical databases: cdns": "T1596.004",
    "search open technical databases: scan databases": "T1596.005",
    "search closed sources": "T1597",
    "search closed sources: threat intel vendors": "T1597.001",
    "network boundary bridging": "T1599",
    "network boundary bridging: network address translation traversal": "T1599.001",
    "weaken encryption": "T1600",
    "weaken encryption: reduce key space": "T1600.001",
    "weaken encryption: disable crypto hardware": "T1600.002",
    "modify system image": "T1601",
    "modify system image: patch system image": "T1601.001",
    "modify system image: downgrade system image": "T1601.002",
    "data from configuration repository": "T1602",
    "data from configuration repository: snmp (mib dump)": "T1602.001",
    "data from configuration repository: network device configuration dump": "T1602.002",
    "stage capabilities: link target": "T1608.005",
    "container administration command": "T1609",
    "deploy container": "T1610",
    "escape to host": "T1611",
    "build image on host": "T1612",
    "group policy discovery": "T1615",
}


class TrainingData(object):
    def __init__(self):
        self.mappings = {}  # Mapping is sentence text plus a list of Attack IDs

    def add_mapping(self, sentence_text, attack_id=None):
        mappings = self.mappings.get(sentence_text, [])  # Get mappings or empty list

        if attack_id:  # If attack_id is specified, add it to the list
            if attack_id not in mappings:
                mappings.append(attack_id)

        self.mappings[sentence_text] = mappings  # Put the mapping list back in

    def to_report_export_serializer_json(self):
        """Creates a dict that can be used to create
        a serializers.ReportExportSerializer instance
        """
        utc_now = datetime.utcnow().isoformat() + "Z"
        res_json = {
            "name": "Bootstrap Training Data",
            "text": "There is no text for this report. These sentences were mapped by human analysts.",
            "ml_model": "humans",
            "created_on": utc_now,
            "updated_on": utc_now,
            "sentences": [],
        }

        order = 0
        for sentence_text, mappings in self.mappings.items():
            if len(sentence_text.strip()) == 0:  # Skip empty sentences
                continue

            is_present = is_present_in_existing_database(sentence_text)

            sentence = {
                "text": sentence_text,
                "order": order,
                "disposition": "accept",
                "mappings": [],
            }

            order += 1

            for mapping in mappings:
                if is_present_in_existing_database(sentence_text):
                    mapping = {"attack_id": mapping, "confidence": "10.0"}
                else:
                    mapping = {"attack_id": mapping, "confidence": "100.0"}
                sentence["mappings"].append(mapping)
            res_json["sentences"].append(sentence)

        return res_json


def get_attack_id(description):
    """Given a description, get the ATTACK ID. Raises IndexError if the retrieval fails."""
    lower_description = description.lower()
    attack_id = ATTACK_LOOKUP[lower_description]
    # attack_id = ATTACK_LOOKUP[description]
    return attack_id


def is_present_in_existing_database(line):
    parent_directory = os.getcwd()
    file_path = (
        parent_directory + "/data/training/training-dataset/tram_existing_dataset_.txt"
    )

    f = open(
        file_path,
        "r",
    )
    existing_data = f.readlines()
    # existing_data = list(set(existing_data))
    if line + "\n" in existing_data:
        return True
    else:
        return False


def main():

    parent_directory = os.getcwd()

    file_path = parent_directory + "/data/training/archive/all_analyzed_reports.json"

    with open(
        file_path,
        encoding="utf-8-sig",
    ) as f:
        all_analyzed_reports = json.load(f)

    with open(parent_directory + "/data/training/archive/negative_data.json") as f:
        negative_data = json.load(f)

    training_data = TrainingData()

    # Add the positives
    for key, value in all_analyzed_reports.items():
        if key.endswith("-multi"):  # It's a multi-mapping, value is a dictionary
            for sentence in value[
                "sentances"
            ]:  # Sentences is misspelled in the source data
                map(
                    partial(training_data.add_mapping, sentence),
                    [ATTACK_LOOKUP[name.lower()] for name in value["technique_names"]],
                )
        else:  # It's a single-mapping, value is a list of sentences
            technique_id = get_attack_id(key)
            for sentence in value:
                training_data.add_mapping(sentence, technique_id)

    # Add the negatives
    for sentence in negative_data:
        training_data.add_mapping(sentence, None)
    res_json = training_data.to_report_export_serializer_json()

    res = ReportExportSerializer(data=res_json)
    res.is_valid(raise_exception=True)

    with open(outfile, "w") as f:
        json.dump(res.initial_data, f, indent=4)

    logger.info("Wrote data to %s" % outfile)


if __name__ == "__main__":
    main()
