# Generated by Django 3.2.6 on 2021-12-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0007_auto_20210818_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stix_id', models.CharField(max_length=128, unique=True)),
                ('attack_id', models.CharField(max_length=128, unique=True)),
                ('attack_url', models.CharField(max_length=512)),
                ('matrix', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
