FROM nginx:1.21.5-alpine

# OCI labels
LABEL "org.opencontainers.image.title"="TRAM"
LABEL "org.opencontainers.image.url"="https://ctid.mitre-engenuity.org/our-work/tram/"
LABEL "org.opencontainers.image.source"="https://github.com/center-for-threat-informed-defense/tram"
LABEL "org.opencontainers.image.description"="Threat Report ATT&CK Mapper - Nginx Component"

# Use the TRAM nginx configuration to proxy
COPY ./docker/nginx-tram.conf /etc/nginx/conf.d/default.conf
