# Generated by Django 3.1.6 on 2021-02-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='document',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='document',
        ),
        migrations.AddField(
            model_name='indicator',
            name='value',
            field=models.CharField(default='dummyinput', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='ml_model',
            field=models.CharField(default='dummymoel', max_length=200),
            preserve_default=False,
        ),
    ]
