# Generated by Django 3.1.7 on 2021-03-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='disposition',
        ),
        migrations.AddField(
            model_name='sentence',
            name='disposition',
            field=models.CharField(blank=True, choices=[('accept', 'Accepted'), ('reject', 'Rejected'), (None, 'No Disposition')], default=None, max_length=200, null=True),
        ),
    ]
