# Generated by Django 3.1.6 on 2021-02-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0002_documentprocessingqueue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentProcessingQueue',
            new_name='DocumentProcessingJob',
        ),
    ]
