# Generated by Django 3.1.6 on 2021-02-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0002_auto_20210219_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='indicator_type',
            field=models.CharField(default='MD5', max_length=200),
            preserve_default=False,
        ),
    ]
