# Generated by Django 3.1.6 on 2021-02-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0003_indicator_indicator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='disposition',
            field=models.CharField(choices=[('accept', 'Accepted'), ('reject', 'Rejected')], default='accept', max_length=200),
            preserve_default=False,
        ),
    ]
