# Generated by Django 3.1.6 on 2021-03-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0004_sentence_disposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackTechnique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stix_id', models.CharField(max_length=128)),
                ('attack_id', models.CharField(max_length=128)),
                ('attack_url', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='sentence',
            name='disposition',
            field=models.CharField(choices=[('accept', 'Accepted'), ('reject', 'Rejected')], default='accept', max_length=200),
        ),
    ]
