# Generated by Django 3.1.6 on 2021-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0005_auto_20210304_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacktechnique',
            name='attack_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='attacktechnique',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='attacktechnique',
            name='stix_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
