# Generated by Django 3.1.12 on 2021-06-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0005_auto_20210429_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='attacktechnique',
            name='sentences',
            field=models.ManyToManyField(through='tram.Mapping', to='tram.Sentence'),
        ),
    ]
