# Generated by Django 3.1.6 on 2021-03-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0006_auto_20210304_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacktechnique',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
