# Generated by Django 3.1.6 on 2021-03-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0007_auto_20210304_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacktechnique',
            name='platform',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
