# Generated by Django 3.2.6 on 2021-12-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0008_attackgroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttackTechnique',
            new_name='AttackObject',
        ),
        migrations.DeleteModel(
            name='AttackGroup',
        ),
        migrations.RenameField(
            model_name='mapping',
            old_name='attack_technique',
            new_name='attack_object',
        ),
    ]
