# Generated by Django 3.1.6 on 2021-03-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0008_attacktechnique_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attacktechnique',
            old_name='platform',
            new_name='matrix',
        ),
    ]
