# Generated by Django 3.2.6 on 2021-12-02 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0008_attackgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGroupMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('attack_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.attackgroup')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTechniqueMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('attack_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.attacktechnique')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.report')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceTechniqueMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('attack_technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tram.attacktechnique')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.report')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.sentence')),
            ],
        ),
        migrations.RenameModel(
            old_name='Mapping',
            new_name='SentenceGroupMapping',
        ),
        migrations.DeleteModel(
            name='MLSettings',
        ),
        migrations.RemoveField(
            model_name='sentencegroupmapping',
            name='attack_technique',
        ),
        migrations.AddField(
            model_name='sentencegroupmapping',
            name='attack_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tram.attackgroup'),
        ),
        migrations.AlterField(
            model_name='attacktechnique',
            name='sentences',
            field=models.ManyToManyField(through='tram.SentenceTechniqueMapping', to='tram.Sentence'),
        ),
    ]
