# Generated by Django 3.1.6 on 2021-03-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0009_auto_20210304_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='disposition',
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('disposition', models.CharField(choices=[('accept', 'Accepted'), ('reject', 'Rejected')], default='accept', max_length=200)),
                ('attack_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.attacktechnique')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.sentence')),
            ],
        ),
    ]
