# Generated by Django 3.2.6 on 2021-12-03 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0009_auto_20211202_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ml_model',
        ),
    ]
