# Generated by Django 3.2.6 on 2021-12-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0009_adversary_adversarymapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adversary',
            name='report',
        ),
    ]
