# Generated by Django 3.1.6 on 2021-03-05 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0010_auto_20210305_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='sentence',
        ),
        migrations.AddField(
            model_name='mapping',
            name='report',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tram.report'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
    ]
