# Generated by Django 3.2.6 on 2021-12-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0010_auto_20211209_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ml_model',
        ),
        migrations.AddField(
            model_name='mapping',
            name='ml_model',
            field=models.CharField(default='tmp_model', max_length=200),
            preserve_default=False,
        ),
    ]
