# Generated by Django 3.1.6 on 2021-03-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0012_mapping_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='attack_technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tram.attacktechnique'),
        ),
    ]
