# Generated by Django 3.1.7 on 2021-03-05 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0013_auto_20210305_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='text',
            field=models.TextField(default='test-text'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.document')),
            ],
            options={
                'unique_together': {('text', 'document')},
            },
        ),
        migrations.AlterField(
            model_name='mapping',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tram.sentence'),
        ),
    ]
