# Generated by Django 3.1.7 on 2021-03-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tram', '0014_auto_20210305_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='order',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterUniqueTogether(
            name='sentence',
            unique_together=set(),
        ),
    ]
