import json
import logging

from django.conf import settings
from django.core.management.base import BaseCommand

from tram.models import AttackObject

LOAD = "load"
CLEAR = "clear"
logger = logging.getLogger(__name__)


STIX_TYPE_TO_ATTACK_TYPE = {
    "attack-pattern": "technique",
    "course-of-action": "mitigation",
    "intrusion-set": "group",
    "malware": "software",
    "tool": "software",
    "x-mitre-tactic": "tactic",
    "x-mitre-data-source": "data_source",
}

ATTACK_LOOKUP = {
    "T1001": "data obfuscation",
    "T1001.001": "data obfuscation: junk data",
    "T1001.002": "data obfuscation: steganography",
    "T1001.003": "data obfuscation: protocol impersonation",
    "T1003": "os credential dumping",
    "T1003.001": "os credential dumping: lsass memory",
    "T1003.002": "os credential dumping: security account manager",
    "T1003.003": "os credential dumping: ntds",
    "T1003.004": "os credential dumping: lsa secrets",
    "T1003.005": "os credential dumping: cached domain credentials",
    "T1003.006": "os credential dumping: dcsync",
    "T1003.007": "os credential dumping: proc filesystem",
    "T1003.008": "os credential dumping: /etc/passwd and /etc/shadow",
    "T1005": "data from local system",
    "T1006": "direct volume access",
    "T1007": "system service discovery",
    "T1008": "fallback channels",
    "T1010": "application window discovery",
    "T1011": "exfiltration over other network medium",
    "T1011.001": "exfiltration over other network medium: exfiltration over bluetooth",
    "T1012": "query registry",
    "T1014": "rootkit",
    "T1016": "system network configuration discovery",
    "T1016.001": "system network configuration discovery: internet connection discovery",
    "T1018": "remote system discovery",
    "T1020": "automated exfiltration",
    "T1020.001": "automated exfiltration: traffic duplication",
    "T1021": "remote services",
    "T1021.001": "remote services: remote desktop protocol",
    "T1021.002": "remote services: smb/windows admin shares",
    "T1021.003": "remote services: distributed component object model",
    "T1021.004": "remote services: ssh",
    "T1021.005": "remote services: vnc",
    "T1021.006": "remote services: windows remote management",
    "T1025": "data from removable media",
    "T1027": "obfuscated files or information",
    "T1027.001": "obfuscated files or information: binary padding",
    "T1027.002": "obfuscated files or information: software packing",
    "T1027.003": "obfuscated files or information: steganography",
    "T1027.004": "obfuscated files or information: compile after delivery",
    "T1027.005": "obfuscated files or information: indicator removal from tools",
    "T1027.006": "obfuscated files or information: html smuggling",
    "T1029": "scheduled transfer",
    "T1030": "data transfer size limits",
    "T1033": "system owner/user discovery",
    "T1036": "masquerading",
    "T1036.001": "masquerading: invalid code signature",
    "T1036.002": "masquerading: right-to-left override",
    "T1036.003": "masquerading: rename system utilities",
    "T1036.004": "masquerading: masquerade task or service",
    "T1036.005": "masquerading: match legitimate name or location",
    "T1036.006": "masquerading: space after filename",
    "T1036.007": "masquerading: double file extension",
    "T1037": "boot or logon initialization scripts",
    "T1037.001": "boot or logon initialization scripts: logon script (windows)",
    "T1037.002": "boot or logon initialization scripts: login hook",
    "T1037.003": "boot or logon initialization scripts: network logon script",
    "T1037.004": "boot or logon initialization scripts: rc scripts",
    "T1037.005": "boot or logon initialization scripts: startup items",
    "T1039": "data from network shared drive",
    "T1040": "network sniffing",
    "T1041": "exfiltration over c2 channel",
    "T1046": "network service discovery",
    "T1047": "windows management instrumentation",
    "T1048": "exfiltration over alternative protocol",
    "T1048.001": "exfiltration over alternative protocol: exfiltration over symmetric encrypted non-c2 protocol",
    "T1048.002": "exfiltration over alternative protocol: exfiltration over asymmetric encrypted non-c2 protocol",
    "T1048.003": "exfiltration over alternative protocol: exfiltration over unencrypted non-c2 protocol",
    "T1049": "system network connections discovery",
    "T1052": "exfiltration over physical medium",
    "T1052.001": "exfiltration over physical medium: exfiltration over usb",
    "T1053": "scheduled task/job",
    "T1053.002": "scheduled task/job: at",
    "T1053.003": "scheduled task/job: cron",
    "T1053.005": "scheduled task/job: scheduled task",
    "T1053.006": "scheduled task/job: systemd timers",
    "T1053.007": "scheduled task/job: container orchestration job",
    "T1055": "process injection",
    "T1055.001": "process injection: dynamic-link library injection",
    "T1055.002": "process injection: portable executable injection",
    "T1055.003": "process injection: thread execution hijacking",
    "T1055.004": "process injection: asynchronous procedure call",
    "T1055.005": "process injection: thread local storage",
    "T1055.008": "process injection: ptrace system calls",
    "T1055.009": "process injection: proc memory",
    "T1055.011": "process injection: extra window memory injection",
    "T1055.012": "process injection: process hollowing",
    "T1055.013": "process injection: process doppelgänging",
    "T1055.014": "process injection: vdso hijacking",
    "T1055.015": "process injection: listplanting",
    "T1056": "input capture",
    "T1056.001": "input capture: keylogging",
    "T1056.002": "input capture: gui input capture",
    "T1056.003": "input capture: web portal capture",
    "T1056.004": "input capture: credential api hooking",
    "T1057": "process discovery",
    "T1059": "command and scripting interpreter",
    "T1059.001": "command and scripting interpreter: powershell",
    "T1059.002": "command and scripting interpreter: applescript",
    "T1059.003": "command and scripting interpreter: windows command shell",
    "T1059.004": "command and scripting interpreter: unix shell",
    "T1059.005": "command and scripting interpreter: visual basic",
    "T1059.006": "command and scripting interpreter: python",
    "T1059.007": "command and scripting interpreter: javascript",
    "T1059.008": "command and scripting interpreter: network device cli",
    "T1068": "exploitation for privilege escalation",
    "T1069": "permission groups discovery",
    "T1069.001": "permission groups discovery: local groups",
    "T1069.002": "permission groups discovery: domain groups",
    "T1069.003": "permission groups discovery: cloud groups",
    "T1070": "indicator removal on host",
    "T1070.001": "indicator removal on host: clear windows event logs",
    "T1070.002": "indicator removal on host: clear linux or mac system logs",
    "T1070.003": "indicator removal on host: clear command history",
    "T1070.004": "indicator removal on host: file deletion",
    "T1070.005": "indicator removal on host: network share connection removal",
    "T1070.006": "indicator removal on host: timestomp",
    "T1071": "application layer protocol",
    "T1071.001": "application layer protocol: web protocols",
    "T1071.002": "application layer protocol: file transfer protocols",
    "T1071.003": "application layer protocol: mail protocols",
    "T1071.004": "application layer protocol: dns",
    "T1072": "software deployment tools",
    "T1074": "data staged",
    "T1074.001": "data staged: local data staging",
    "T1074.002": "data staged: remote data staging",
    "T1078": "valid accounts",
    "T1078.001": "valid accounts: default accounts",
    "T1078.002": "valid accounts: domain accounts",
    "T1078.003": "valid accounts: local accounts",
    "T1078.004": "valid accounts: cloud accounts",
    "T1080": "taint shared content",
    "T1082": "system information discovery",
    "T1083": "file and directory discovery",
    "T1087": "account discovery",
    "T1087.001": "account discovery: local account",
    "T1087.002": "account discovery: domain account",
    "T1087.003": "account discovery: email account",
    "T1087.004": "account discovery: cloud account",
    "T1090": "proxy",
    "T1090.001": "proxy: internal proxy",
    "T1090.002": "proxy: external proxy",
    "T1090.003": "proxy: multi-hop proxy",
    "T1090.004": "proxy: domain fronting",
    "T1091": "replication through removable media",
    "T1092": "communication through removable media",
    "T1095": "non-application layer protocol",
    "T1098": "account manipulation",
    "T1098.001": "account manipulation: additional cloud credentials",
    "T1098.002": "account manipulation: additional email delegate permissions",
    "T1098.003": "account manipulation: additional cloud roles",
    "T1098.004": "account manipulation: ssh authorized keys",
    "T1098.005": "account manipulation: device registration",
    "T1102": "web service",
    "T1102.001": "web service: dead drop resolver",
    "T1102.002": "web service: bidirectional communication",
    "T1102.003": "web service: one-way communication",
    "T1104": "multi-stage channels",
    "T1105": "ingress tool transfer",
    "T1106": "native api",
    "T1110": "brute force",
    "T1110.001": "brute force: password guessing",
    "T1110.002": "brute force: password cracking",
    "T1110.003": "brute force: password spraying",
    "T1110.004": "brute force: credential stuffing",
    "T1111": "multi-factor authentication interception",
    "T1112": "modify registry",
    "T1113": "screen capture",
    "T1114": "email collection",
    "T1114.001": "email collection: local email collection",
    "T1114.002": "email collection: remote email collection",
    "T1114.003": "email collection: email forwarding rule",
    "T1115": "clipboard data",
    "T1119": "automated collection",
    "T1120": "peripheral device discovery",
    "T1123": "audio capture",
    "T1124": "system time discovery",
    "T1125": "video capture",
    "T1127": "trusted developer utilities proxy execution",
    "T1127.001": "trusted developer utilities proxy execution: msbuild",
    "T1129": "shared modules",
    "T1132": "data encoding",
    "T1132.001": "data encoding: standard encoding",
    "T1132.002": "data encoding: non-standard encoding",
    "T1133": "external remote services",
    "T1134": "access token manipulation",
    "T1134.001": "access token manipulation: token impersonation/theft",
    "T1134.002": "access token manipulation: create process with token",
    "T1134.003": "access token manipulation: make and impersonate token",
    "T1134.004": "access token manipulation: parent pid spoofing",
    "T1134.005": "access token manipulation: sid-history injection",
    "T1135": "network share discovery",
    "T1136": "create account",
    "T1136.001": "create account: local account",
    "T1136.002": "create account: domain account",
    "T1136.003": "create account: cloud account",
    "T1137": "office application startup",
    "T1137.001": "office application startup: office template macros",
    "T1137.002": "office application startup: office test",
    "T1137.003": "office application startup: outlook forms",
    "T1137.004": "office application startup: outlook home page",
    "T1137.005": "office application startup: outlook rules",
    "T1137.006": "office application startup: add-ins",
    "T1140": "deobfuscate/decode files or information",
    "T1176": "browser extensions",
    "T1185": "browser session hijacking",
    "T1187": "forced authentication",
    "T1189": "drive-by compromise",
    "T1190": "exploit public-facing application",
    "T1195": "supply chain compromise",
    "T1195.001": "supply chain compromise: compromise software dependencies and development tools",
    "T1195.002": "supply chain compromise: compromise software supply chain",
    "T1195.003": "supply chain compromise: compromise hardware supply chain",
    "T1197": "bits jobs",
    "T1199": "trusted relationship",
    "T1200": "hardware additions",
    "T1201": "password policy discovery",
    "T1202": "indirect command execution",
    "T1203": "exploitation for client execution",
    "T1204": "user execution",
    "T1204.001": "user execution: malicious link",
    "T1204.002": "user execution: malicious file",
    "T1204.003": "user execution: malicious image",
    "T1205": "traffic signaling",
    "T1205.001": "traffic signaling: port knocking",
    "T1207": "rogue domain controller",
    "T1210": "exploitation of remote services",
    "T1211": "exploitation for defense evasion",
    "T1212": "exploitation for credential access",
    "T1213": "data from information repositories",
    "T1213.001": "data from information repositories: confluence",
    "T1213.002": "data from information repositories: sharepoint",
    "T1213.003": "data from information repositories: code repositories",
    "T1216": "system script proxy execution",
    "T1216.001": "system script proxy execution: pubprn",
    "T1217": "browser bookmark discovery",
    "T1218": "system binary proxy execution",
    "T1218.001": "system binary proxy execution: compiled html file",
    "T1218.002": "system binary proxy execution: control panel",
    "T1218.003": "system binary proxy execution: cmstp",
    "T1218.004": "system binary proxy execution: installutil",
    "T1218.005": "system binary proxy execution: mshta",
    "T1218.007": "system binary proxy execution: msiexec",
    "T1218.008": "system binary proxy execution: odbcconf",
    "T1218.009": "system binary proxy execution: regsvcs/regasm",
    "T1218.010": "system binary proxy execution: regsvr32",
    "T1218.011": "system binary proxy execution: rundll32",
    "T1218.012": "system binary proxy execution: verclsid",
    "T1218.013": "system binary proxy execution: mavinject",
    "T1218.014": "system binary proxy execution: mmc",
    "T1219": "remote access software",
    "T1220": "xsl script processing",
    "T1221": "template injection",
    "T1222": "file and directory permissions modification",
    "T1222.001": "file and directory permissions modification: windows file and directory permissions modification",
    "T1222.002": "file and directory permissions modification: linux and mac file and directory permissions modification",
    "T1480": "execution guardrails",
    "T1480.001": "execution guardrails: environmental keying",
    "T1482": "domain trust discovery",
    "T1484": "domain policy modification",
    "T1484.001": "domain policy modification: group policy modification",
    "T1484.002": "domain policy modification: domain trust modification",
    "T1485": "data destruction",
    "T1486": "data encrypted for impact",
    "T1489": "service stop",
    "T1490": "inhibit system recovery",
    "T1491": "defacement",
    "T1491.001": "defacement: internal defacement",
    "T1491.002": "defacement: external defacement",
    "T1495": "firmware corruption",
    "T1496": "resource hijacking",
    "T1497": "virtualization/sandbox evasion",
    "T1497.001": "virtualization/sandbox evasion: system checks",
    "T1497.002": "virtualization/sandbox evasion: user activity based checks",
    "T1497.003": "virtualization/sandbox evasion: time based evasion",
    "T1498": "network denial of service",
    "T1498.001": "network denial of service: direct network flood",
    "T1498.002": "network denial of service: reflection amplification",
    "T1499": "endpoint denial of service",
    "T1499.001": "endpoint denial of service: os exhaustion flood",
    "T1499.002": "endpoint denial of service: service exhaustion flood",
    "T1499.003": "endpoint denial of service: application exhaustion flood",
    "T1499.004": "endpoint denial of service: application or system exploitation",
    "T1505": "server software component",
    "T1505.001": "server software component: sql stored procedures",
    "T1505.002": "server software component: transport agent",
    "T1505.003": "server software component: web shell",
    "T1505.004": "server software component: iis components",
    "T1505.005": "server software component: terminal services dll",
    "T1518": "software discovery",
    "T1518.001": "software discovery: security software discovery",
    "T1525": "implant internal image",
    "T1526": "cloud service discovery",
    "T1528": "steal application access token",
    "T1529": "system shutdown/reboot",
    "T1530": "data from cloud storage object",
    "T1531": "account access removal",
    "T1534": "internal spearphishing",
    "T1535": "unused/unsupported cloud regions",
    "T1537": "transfer data to cloud account",
    "T1538": "cloud service dashboard",
    "T1539": "steal web session cookie",
    "T1542": "pre-os boot",
    "T1542.001": "pre-os boot: system firmware",
    "T1542.002": "pre-os boot: component firmware",
    "T1542.003": "pre-os boot: bootkit",
    "T1542.004": "pre-os boot: rommonkit",
    "T1542.005": "pre-os boot: tftp boot",
    "T1543": "create or modify system process",
    "T1543.001": "create or modify system process: launch agent",
    "T1543.002": "create or modify system process: systemd service",
    "T1543.003": "create or modify system process: windows service",
    "T1543.004": "create or modify system process: launch daemon",
    "T1546": "event triggered execution",
    "T1546.001": "event triggered execution: change default file association",
    "T1546.002": "event triggered execution: screensaver",
    "T1546.003": "event triggered execution: windows management instrumentation event subscription",
    "T1546.004": "event triggered execution: unix shell configuration modification",
    "T1546.005": "event triggered execution: trap",
    "T1546.006": "event triggered execution: lc_load_dylib addition",
    "T1546.007": "event triggered execution: netsh helper dll",
    "T1546.008": "event triggered execution: accessibility features",
    "T1546.009": "event triggered execution: appcert dlls",
    "T1546.010": "event triggered execution: appinit dlls",
    "T1546.011": "event triggered execution: application shimming",
    "T1546.012": "event triggered execution: image file execution options injection",
    "T1546.013": "event triggered execution: powershell profile",
    "T1546.014": "event triggered execution: emond",
    "T1546.015": "event triggered execution: component object model hijacking",
    "T1547": "boot or logon autostart execution",
    "T1547.001": "boot or logon autostart execution: registry run keys / startup folder",
    "T1547.002": "boot or logon autostart execution: authentication package",
    "T1547.003": "boot or logon autostart execution: time providers",
    "T1547.004": "boot or logon autostart execution: winlogon helper dll",
    "T1547.005": "boot or logon autostart execution: security support provider",
    "T1547.006": "boot or logon autostart execution: kernel modules and extensions",
    "T1547.007": "boot or logon autostart execution: re-opened applications",
    "T1547.008": "boot or logon autostart execution: lsass driver",
    "T1547.009": "boot or logon autostart execution: shortcut modification",
    "T1547.010": "boot or logon autostart execution: port monitors",
    "T1547.012": "boot or logon autostart execution: print processors",
    "T1547.013": "boot or logon autostart execution: xdg autostart entries",
    "T1547.014": "boot or logon autostart execution: active setup",
    "T1547.015": "boot or logon autostart execution: login items",
    "T1548": "abuse elevation control mechanism",
    "T1548.001": "abuse elevation control mechanism: setuid and setgid",
    "T1548.002": "abuse elevation control mechanism: bypass user account control",
    "T1548.003": "abuse elevation control mechanism: sudo and sudo caching",
    "T1548.004": "abuse elevation control mechanism: elevated execution with prompt",
    "T1550": "use alternate authentication material",
    "T1550.001": "use alternate authentication material: application access token",
    "T1550.002": "use alternate authentication material: pass the hash",
    "T1550.003": "use alternate authentication material: pass the ticket",
    "T1550.004": "use alternate authentication material: web session cookie",
    "T1552": "unsecured credentials",
    "T1552.001": "unsecured credentials: credentials in files",
    "T1552.002": "unsecured credentials: credentials in registry",
    "T1552.003": "unsecured credentials: bash history",
    "T1552.004": "unsecured credentials: private keys",
    "T1552.005": "unsecured credentials: cloud instance metadata api",
    "T1552.006": "unsecured credentials: group policy preferences",
    "T1552.007": "unsecured credentials: container api",
    "T1553": "subvert trust controls",
    "T1553.001": "subvert trust controls: gatekeeper bypass",
    "T1553.002": "subvert trust controls: code signing",
    "T1553.003": "subvert trust controls: sip and trust provider hijacking",
    "T1553.004": "subvert trust controls: install root certificate",
    "T1553.005": "subvert trust controls: mark-of-the-web bypass",
    "T1553.006": "subvert trust controls: code signing policy modification",
    "T1554": "compromise client software binary",
    "T1555": "credentials from password stores",
    "T1555.001": "credentials from password stores: keychain",
    "T1555.002": "credentials from password stores: securityd memory",
    "T1555.003": "credentials from password stores: credentials from web browsers",
    "T1555.004": "credentials from password stores: windows credential manager",
    "T1555.005": "credentials from password stores: password managers",
    "T1556": "modify authentication process",
    "T1556.001": "modify authentication process: domain controller authentication",
    "T1556.002": "modify authentication process: password filter dll",
    "T1556.003": "modify authentication process: pluggable authentication modules",
    "T1556.004": "modify authentication process: network device authentication",
    "T1556.005": "modify authentication process: reversible encryption",
    "T1557": "adversary-in-the-middle",
    "T1557.001": "adversary-in-the-middle: llmnr/nbt-ns poisoning and smb relay",
    "T1557.002": "adversary-in-the-middle: arp cache poisoning",
    "T1557.003": "adversary-in-the-middle: dhcp spoofing",
    "T1558": "steal or forge kerberos tickets",
    "T1558.001": "steal or forge kerberos tickets: golden ticket",
    "T1558.002": "steal or forge kerberos tickets: silver ticket",
    "T1558.003": "steal or forge kerberos tickets: kerberoasting",
    "T1558.004": "steal or forge kerberos tickets: as-rep roasting",
    "T1559": "inter-process communication",
    "T1559.001": "inter-process communication: component object model",
    "T1559.002": "inter-process communication: dynamic data exchange",
    "T1559.003": "inter-process communication: xpc services",
    "T1560": "archive collected data",
    "T1560.001": "archive collected data: archive via utility",
    "T1560.002": "archive collected data: archive via library",
    "T1560.003": "archive collected data: archive via custom method",
    "T1561": "disk wipe",
    "T1561.001": "disk wipe: disk content wipe",
    "T1561.002": "disk wipe: disk structure wipe",
    "T1562": "impair defenses",
    "T1562.001": "impair defenses: disable or modify tools",
    "T1562.002": "impair defenses: disable windows event logging",
    "T1562.003": "impair defenses: impair command history logging",
    "T1562.004": "impair defenses: disable or modify system firewall",
    "T1562.006": "impair defenses: indicator blocking",
    "T1562.007": "impair defenses: disable or modify cloud firewall",
    "T1562.008": "impair defenses: disable cloud logs",
    "T1562.009": "impair defenses: safe mode boot",
    "T1562.010": "impair defenses: downgrade attack",
    "T1563": "remote service session hijacking",
    "T1563.001": "remote service session hijacking: ssh hijacking",
    "T1563.002": "remote service session hijacking: rdp hijacking",
    "T1564": "hide artifacts",
    "T1564.001": "hide artifacts: hidden files and directories",
    "T1564.002": "hide artifacts: hidden users",
    "T1564.003": "hide artifacts: hidden window",
    "T1564.004": "hide artifacts: ntfs file attributes",
    "T1564.005": "hide artifacts: hidden file system",
    "T1564.006": "hide artifacts: run virtual instance",
    "T1564.007": "hide artifacts: vba stomping",
    "T1564.008": "hide artifacts: email hiding rules",
    "T1564.009": "hide artifacts: resource forking",
    "T1564.010": "hide artifacts: process argument spoofing",
    "T1565": "data manipulation",
    "T1565.001": "data manipulation: stored data manipulation",
    "T1565.002": "data manipulation: transmitted data manipulation",
    "T1565.003": "data manipulation: runtime data manipulation",
    "T1566": "phishing",
    "T1566.001": "phishing: spearphishing attachment",
    "T1566.002": "phishing: spearphishing link",
    "T1566.003": "phishing: spearphishing via service",
    "T1567": "exfiltration over web service",
    "T1567.001": "exfiltration over web service: exfiltration to code repository",
    "T1567.002": "exfiltration over web service: exfiltration to cloud storage",
    "T1568": "dynamic resolution",
    "T1568.001": "dynamic resolution: fast flux dns",
    "T1568.002": "dynamic resolution: domain generation algorithms",
    "T1568.003": "dynamic resolution: dns calculation",
    "T1569": "system services",
    "T1569.001": "system services: launchctl",
    "T1569.002": "system services: service execution",
    "T1570": "lateral tool transfer",
    "T1571": "non-standard port",
    "T1572": "protocol tunneling",
    "T1573": "encrypted channel",
    "T1573.001": "encrypted channel: symmetric cryptography",
    "T1573.002": "encrypted channel: asymmetric cryptography",
    "T1574": "hijack execution flow",
    "T1574.001": "hijack execution flow: dll search order hijacking",
    "T1574.002": "hijack execution flow: dll side-loading",
    "T1574.004": "hijack execution flow: dylib hijacking",
    "T1574.005": "hijack execution flow: executable installer file permissions weakness",
    "T1574.006": "hijack execution flow: dynamic linker hijacking",
    "T1574.007": "hijack execution flow: path interception by path environment variable",
    "T1574.008": "hijack execution flow: path interception by search order hijacking",
    "T1574.009": "hijack execution flow: path interception by unquoted path",
    "T1574.010": "hijack execution flow: services file permissions weakness",
    "T1574.011": "hijack execution flow: services registry permissions weakness",
    "T1574.012": "hijack execution flow: cor_profiler",
    "T1574.013": "hijack execution flow: kernelcallbacktable",
    "T1578": "modify cloud compute infrastructure",
    "T1578.001": "modify cloud compute infrastructure: create snapshot",
    "T1578.002": "modify cloud compute infrastructure: create cloud instance",
    "T1578.003": "modify cloud compute infrastructure: delete cloud instance",
    "T1578.004": "modify cloud compute infrastructure: revert cloud instance",
    "T1580": "cloud infrastructure discovery",
    "T1583": "acquire infrastructure",
    "T1583.001": "acquire infrastructure: domains",
    "T1583.002": "acquire infrastructure: dns server",
    "T1583.003": "acquire infrastructure: virtual private server",
    "T1583.004": "acquire infrastructure: server",
    "T1583.005": "acquire infrastructure: botnet",
    "T1583.006": "acquire infrastructure: web services",
    "T1584": "compromise infrastructure",
    "T1584.001": "compromise infrastructure: domains",
    "T1584.002": "compromise infrastructure: dns server",
    "T1584.003": "compromise infrastructure: virtual private server",
    "T1584.004": "compromise infrastructure: server",
    "T1584.005": "compromise infrastructure: botnet",
    "T1584.006": "compromise infrastructure: web services",
    "T1585": "establish accounts",
    "T1585.001": "establish accounts: social media accounts",
    "T1585.002": "establish accounts: email accounts",
    "T1586": "compromise accounts",
    "T1586.001": "compromise accounts: social media accounts",
    "T1586.002": "compromise accounts: email accounts",
    "T1587": "develop capabilities",
    "T1587.001": "develop capabilities: malware",
    "T1587.002": "develop capabilities: code signing certificates",
    "T1587.003": "develop capabilities: digital certificates",
    "T1587.004": "develop capabilities: exploits",
    "T1588": "obtain capabilities",
    "T1588.001": "obtain capabilities: malware",
    "T1588.002": "obtain capabilities: tool",
    "T1588.003": "obtain capabilities: code signing certificates",
    "T1588.004": "obtain capabilities: digital certificates",
    "T1588.005": "obtain capabilities: exploits",
    "T1588.006": "obtain capabilities: vulnerabilities",
    "T1589": "gather victim identity information",
    "T1589.001": "gather victim identity information: credentials",
    "T1589.002": "gather victim identity information: email addresses",
    "T1589.003": "gather victim identity information: employee names",
    "T1590": "gather victim network information",
    "T1590.001": "gather victim network information: domain properties",
    "T1590.002": "gather victim network information: dns",
    "T1590.003": "gather victim network information: network trust dependencies",
    "T1590.004": "gather victim network information: network topology",
    "T1590.005": "gather victim network information: ip addresses",
    "T1590.006": "gather victim network information: network security appliances",
    "T1591": "gather victim org information",
    "T1591.001": "gather victim org information: determine physical locations",
    "T1591.002": "gather victim org information: business relationships",
    "T1591.003": "gather victim org information: identify business tempo",
    "T1591.004": "gather victim org information: identify roles",
    "T1592": "gather victim host information",
    "T1592.001": "gather victim host information: hardware",
    "T1592.002": "gather victim host information: software",
    "T1592.003": "gather victim host information: firmware",
    "T1592.004": "gather victim host information: client configurations",
    "T1593": "search open websites/domains",
    "T1593.001": "search open websites/domains: social media",
    "T1593.002": "search open websites/domains: search engines",
    "T1594": "search victim-owned websites",
    "T1595": "active scanning",
    "T1595.001": "active scanning: scanning ip blocks",
    "T1595.002": "active scanning: vulnerability scanning",
    "T1595.003": "active scanning: wordlist scanning",
    "T1596": "search open technical databases",
    "T1596.001": "search open technical databases: dns/passive dns",
    "T1596.002": "search open technical databases: whois",
    "T1596.003": "search open technical databases: digital certificates",
    "T1596.004": "search open technical databases: cdns",
    "T1596.005": "search open technical databases: scan databases",
    "T1597": "search closed sources",
    "T1597.001": "search closed sources: threat intel vendors",
    "T1597.002": "search closed sources: purchase technical data",
    "T1598": "phishing for information",
    "T1598.001": "phishing for information: spearphishing service",
    "T1598.002": "phishing for information: spearphishing attachment",
    "T1598.003": "phishing for information: spearphishing link",
    "T1599": "network boundary bridging",
    "T1599.001": "network boundary bridging: network address translation traversal",
    "T1600": "weaken encryption",
    "T1600.001": "weaken encryption: reduce key space",
    "T1600.002": "weaken encryption: disable crypto hardware",
    "T1601": "modify system image",
    "T1601.001": "modify system image: patch system image",
    "T1601.002": "modify system image: downgrade system image",
    "T1602": "data from configuration repository",
    "T1602.001": "data from configuration repository: snmp (mib dump)",
    "T1602.002": "data from configuration repository: network device configuration dump",
    "T1606": "forge web credentials",
    "T1606.001": "forge web credentials: web cookies",
    "T1606.002": "forge web credentials: saml tokens",
    "T1608": "stage capabilities",
    "T1608.001": "stage capabilities: upload malware",
    "T1608.002": "stage capabilities: upload tool",
    "T1608.003": "stage capabilities: install digital certificate",
    "T1608.004": "stage capabilities: drive-by target",
    "T1608.005": "stage capabilities: link target",
    "T1609": "container administration command",
    "T1610": "deploy container",
    "T1611": "escape to host",
    "T1612": "build image on host",
    "T1613": "container and resource discovery",
    "T1614": "system location discovery",
    "T1614.001": "system location discovery: system language discovery",
    "T1615": "group policy discovery",
    "T1619": "cloud storage object discovery",
    "T1620": "reflective code loading",
    "T1621": "multi-factor authentication request generation",
    "T1622": "debugger evasion",
    "T1647": "plist file modification",
}


inserted_ids = set()


class Command(BaseCommand):
    help = "Machine learning pipeline commands"

    def add_arguments(self, parser):
        sp = parser.add_subparsers(
            title="subcommands", dest="subcommand", required=True
        )
        sp.add_parser(LOAD, help="Load ATT&CK Data into the Database")
        sp.add_parser(CLEAR, help="Clear ATT&CK Data from the Database")

    def clear_attack_data(self):
        deleted = AttackObject.objects.all().delete()
        logger.info("Deleted %d Attack objects", deleted[0])

    def create_attack_object(self, obj):

        if "external_references" in obj.keys():
            for external_reference in obj["external_references"]:
                if external_reference["source_name"] not in (
                    "mitre-attack",
                    "mitre-pre-attack",
                    "mitre-mobile-attack",
                ):
                    continue

                attack_id = external_reference["external_id"]
                attack_url = external_reference["url"]
                matrix = external_reference["source_name"]
            if (
                "S" not in attack_id
                and "G" not in attack_id
                and "DS" not in attack_id
                and "TA" not in attack_id
            ):
                assert attack_id is not None
                assert attack_url is not None
                assert matrix is not None

                print(attack_id, attack_url, matrix)

                stix_type = obj["type"]
                attack_type = STIX_TYPE_TO_ATTACK_TYPE[stix_type]
                status = ""
                if attack_id not in inserted_ids and attack_id in ATTACK_LOOKUP.keys():
                    inserted_ids.add(attack_id)
                    obj, status = AttackObject.objects.get_or_create(
                        name=obj["name"],
                        stix_id=obj["id"],
                        stix_type=stix_type,
                        attack_id=attack_id,
                        attack_type=attack_type,
                        attack_url=attack_url,
                        matrix=matrix,
                    )

                return obj, status
        return False, False

    def load_attack_data(self, filepath):
        created_stats = {}
        skipped_stats = {}

        with open(filepath, "r") as f:
            attack_json = json.load(f)

        assert attack_json["spec_version"] == "2.1"
        assert attack_json["type"] == "bundle"

        for obj in attack_json["objects"]:
            obj_type = obj["type"]

            # TODO: Skip deprecated objects
            if obj.get("revoked", False):  # Skip revoked objects
                skipped_stats[obj_type] = skipped_stats.get(obj_type, 0) + 1
                continue

            if obj_type in (
                "relationship",
                "course-of-action",
                "identity",
                "x-mitre-matrix",
                "marking-definition",
            ):
                skipped_stats[obj_type] = skipped_stats.get(obj_type, 0) + 1
                continue

            try:
                db_obj, created = self.create_attack_object(obj)

                if type(db_obj) == bool:
                    pass
                else:
                    if created:
                        created_stats[obj_type] = created_stats.get(obj_type, 0) + 1
                    else:
                        skipped_stats[obj_type] = skipped_stats.get(obj_type, 0) + 1
            except ValueError:  # Value error means unsupported object type
                skipped_stats[obj_type] = skipped_stats.get(obj_type, 0) + 1

        logger.info("Load stats for %s:", filepath)
        for k, v in created_stats.items():
            logger.info("Created %s %s objects", v, k)
        for k, v in skipped_stats.items():
            logger.info("Skipped %s %s objects", v, k)

    def handle(self, *args, **options):
        subcommand = options["subcommand"]

        if subcommand == LOAD:
            # Note - as of ATT&CK v8.2
            #   Techniques are unique among files, but
            #   Groups are not unique among files
            self.load_attack_data(
                settings.DATA_DIRECTORY / "attack/enterprise-attack.json"
            )
            # self.load_attack_data(settings.DATA_DIRECTORY / "attack/mobile-attack.json")
            # self.load_attack_data(settings.DATA_DIRECTORY / "attack/pre-attack.json")
        elif subcommand == CLEAR:
            self.clear_attack_data()
